services:
  - type: web
    name: gigcampus
    runtime: python
    buildCommand: ./build.sh
    startCommand: sh start.sh
    disk:
      name: gigcampus-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.11
